#!/usr/bin/env bash

DIR="$HOME/.dotfiles"

ACK="$HOME/.ackrc"
BP="$HOME/.bash_profile"
BRC="$HOME/.bashrc"
INPUTRC="$HOME/.inputrc"
GC="$HOME/.gitconfig"
GI="$HOME/.gitignore"
GRC="$HOME/.gvimrc"
IRC="$HOME/.irbrc"
SCREEN="$HOME/.screenrc"
VIM="$HOME/.vim"
VRC="$HOME/.vimrc"
ZSHRC="$HOME/.zshrc"
OHMYZSHCUSTOM="$HOME/.oh-my-zsh/custom"

function erase_dotfiles {
  # echo "Erasing dotfiles..."
  rm -f $ACK
  rm -f $BP
  rm -f $BRC
  rm -f $INPUTRC
  rm -f $GC
  rm -f $GI
  rm -f $GRC
  rm -f $SCREEN
  rm -f $VIM
  rm -f $VRC
  rm -f $ZSHRC

  rm -f $HOME/.i3/config

  rm -f $OHMYZSHCUSTOM/aliases.zsh
  rm -f $OHMYZSHCUSTOM/env.zsh
  rm -f $OHMYZSHCUSTOM/highlighting.zsh
  rm -f $OHMYZSHCUSTOM/themes/my.zsh-theme
  for PLUGIN in "$(ls -A $DIR/zsh/custom/plugins/)"; do
    rm -f $OHMYZSHCUSTOM/plugins/$PLUGIN
  done
}

function create_symlinks {
  # echo "Creating symlinks..."
  ln -s $DIR/ackrc $ACK
  ln -s $DIR/bash/profile $BP
  ln -s $DIR/bash/profile $BRC
  ln -s $DIR/bash/input $INPUTRC
  ln -s $DIR/git/config $GC
  ln -s $DIR/git/ignore $GI
  ln -s $DIR/vim/grc $GRC
  ln -s $DIR/screenrc $SCREEN
  ln -s $DIR/vim $VIM
  ln -s $DIR/vim/rc $VRC
  ln -s $DIR/zsh/rc $ZSHRC

  mkdir -p $HOME/.i3/
  ln -s $DIR/i3/config $HOME/.i3/config

  mkdir -p $OHMYZSHCUSTOM
  ln -s $DIR/zsh/custom/aliases.zsh $OHMYZSHCUSTOM/aliases.zsh
  ln -s $DIR/zsh/custom/env.zsh $OHMYZSHCUSTOM/env.zsh
  ln -s $DIR/zsh/custom/highlighting.zsh $OHMYZSHCUSTOM/highlighting.zsh
  mkdir -p $OHMYZSHCUSTOM/themes
  ln -s $DIR/zsh/custom/themes/my.zsh-theme $OHMYZSHCUSTOM/themes/my.zsh-theme
  mkdir -p $OHMYZSHCUSTOM/plugins
  for PLUGIN in "$(ls -A $DIR/zsh/custom/plugins/)"; do
    ln -s $DIR/zsh/custom/plugins/$PLUGIN $OHMYZSHCUSTOM/plugins/$PLUGIN
  done
}

function get_google_dotfiles {
  if [ -f "~/.at_google" ]; then
    git clone sso://user/bradenw/dotfiles-google ~/.dotfiles-google/
    ~/.dotfiles-google/setup
  fi
}

function setup_zsh {
  if [[ !(-d ~/.oh-my-zsh) ]]; then
    git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  fi
  cd $DIR
  git submodule init zsh/custom/plugins/zsh-syntax-highlighting
  git submodule update zsh/custom/plugins/zsh-syntax-highlighting

  which zsh
  if [[ $? -eq 0 && "$SHELL" != "$(which zsh)" ]]; then
    sudo chsh -s $(which zsh)
  fi
}

# make sure the directory exists
if [ -d $DIR ]; then

  echo "Replace current dotfiles? [1 or 2]"
  select RN in "Replace" "No"; do
    case $RN in
      Replace )
        cd $DIR
        git submodule update --init --recursive
        setup_zsh
        erase_dotfiles
        create_symlinks
        get_google_dotfiles
        exit 0
        ;;
      
      No )
        get_oh_my_zsh
        create_symlinks
        get_google_dotfiles
        exit 0
        ;;
    esac
  done

fi
