#!/usr/bin/env bash
# Set up dotfiles on a remote machine.
# Usage:
# ./setup_dotfiles_remote [remote machine address]

TOP=$(cd $(dirname $0) && pwd)
cd $TOP

cd
tar -czf dotfiles-for-send.tar.gz .dotfiles/
scp dotfiles-for-send.tar.gz $1:~/dotfiles.tar.gz
rm dotfiles-for-send.tar.gz
ssh $1 "cd && tar -xzf dotfiles.tar.gz && ~/.dotfiles/setup_dotfiles"
