#!/usr/bin/env bash
# wrap REPLs with rlwrap for nice cli editing
alias chibi="rlwrap chibi-scheme"
alias clj="rlwrap clj"
alias racket="rlwrap racket"
alias s48="rlwrap scheme48"
alias jdb="rlwrap jdb"

# load gsi with The Little Schemer's base functions
# alias tls="gsi $HOME/Projects/scheme/TLS/base.scm -"

# load racket with The Little Schemer's base functions
alias tls="racket -f $HOME/Projects/scheme/TLS/base.scm -i"

# handy for grepping words from the dictionary
alias words="cat /usr/share/dict/web2 /usr/share/dict/web2a"

alias eclimd="/usr/local/google/users/bradenw/eclipse44/stable/eclimd"
alias yavdb="~/.dotfiles/vim/bundle/yavdb/yavdb"

# laziness
# Ubuntu needs --color=auto, OSX prints an error message every time
if [ "$(ls --color=auto > /dev/null 2>&1 && echo $?)" == "0" ]; then
    alias ls='ls -aGF --color=auto'
    alias ll='ls -lha --color=auto'
    alias grep='grep --color=auto'
else
    alias ls='ls -aGF'
    alias ll='ls -lha'
fi
alias ag="ag --color-match \"0;35\""
alias df='df -h'
alias du='du -h'
alias a="alias"
alias l="l -F"
alias lls="ls -alF"
alias lr="lls -R"
alias lts="lls -t"
alias mv="mv -i"
alias rm="rm -i"
alias cdd="cd -"
alias ..="cd .."
alias h=history

alias g=git
alias s=subl
alias m=subl
alias m1="/Applications/TextMate.app/Contents/SharedSupport/Support/bin/mate"
alias m2=mate
alias v=vim
alias t=todo.sh
alias r=rails

alias bi="brew install"
alias bif="bi --force"
alias bs="brew search"
alias bu="brew update"
alias bo="brew outdated"
alias bup="brew upgrade"
alias bp="brew prune"
alias br="brew rm"
alias bls="brew ls"
alias bll="brew ll"
alias bh="brew home"

alias ga="git add"
alias gaa="git add --all"
alias gb="git branch"
alias gbl="git blame"
alias gd="git diff"
alias gs="git status --ignore-submodules"
alias gp="git pull"
alias go="git push"
alias gm="git commit -m"
alias gma="git commit -am"
alias gl="git log --pretty=oneline"
alias gt="git t"
alias gw="git whatchanged"
alias gcl="git clone"
alias gc="git checkout"
alias gss="git stash save"
alias gsa="git stash apply"
alias gsl="git stash list"
alias gsd="git stash drop"
alias gsc="git stash clear"
alias gsp="git stash pop"

alias jas="jasmine-node --color"
alias mtr="sudo mtr"

alias chrome="google-chrome"
alias chrome-isolated="google-chrome --user-data-dir=~/.config/google-chrome/Profile\ 1/"
function chrome-isolated-proxy() {
  local proxy_server="$1"
  chrome-isolated --proxy-server="http=${proxy_server}"
}

# postgres
alias pg_start="pg_ctl -l /usr/local/var/postgres/server.log start"
alias pg_stop="pg_ctl -D /usr/local/var/postgres stop -s -m fast"

# mysql
alias start_mysql="launchctl load -w $HOME/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
alias stop_mysql="launchctl unload -w $HOME/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
alias restart_mysql="stop_mysql && start_mysql"

# for Lion, in case I forget it
alias show_library="chflags nohidden ~/Library/"
alias hide_library="chflags hidden ~/Library/"

# edit and reload bash configuration
alias ea="v $HOME/.dotfiles/bash/aliases"
alias ee="v $HOME/.dotfiles/bash/env"
alias et="v $HOME/.dotfiles/bash/tools"
alias reload=". $HOME/.bash_profile"

# always color rspec
alias rspec="rspec -c"

# mkdir, cd into it
mkcd() {
  mkdir -p "$*"
  cd "$*"
}

function colortest() {
  bgcolors=( 40 100 41 101 42 102 43 103 44 104 45 105 46 106 47 107 49 )
  fgcolors=( 30 90 31 91 32 92 33 93 34 94 35 95 36 96 37 97 39 )
  colornames=( "-BLK" "+BLK" "-RED" "+RED" "-GRN" "+GRN" "-YEL" "+YEL" "-BLU" "+BLU" "-MAG" "+MAG" "-CYN" "+CYN" "-WHT" "+WHT" " DEF" )
  for j in `seq 0 $(expr ${#bgcolors[@]} - 1)`; do
    printf "\e[0;${fgcolors[j]}m"" ${colornames[j]} "
    for i in `seq 0 $(expr ${#fgcolors[@]} - 1)`; do
      printf "\e[0;${fgcolors[i]};${bgcolors[j]}m"" ${colornames[i]} "
    done;
    printf "\e[0m\n"
  done
}

alias java8="/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/bin/java"
